### ISSUE TITLE
Missing google accounts required parameters

### ISSUE THREAD

**Issue by safarista** [patriciomacadden/fogata#1]
**Request URL:**

``` bash
https://accounts.google.com/o/oauth2/auth?response_type=code&client_id&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fgoogle_oauth2%2Fcallback&state=cf2d7a3dce45af4dec072a372d7485176230e824c17eedb0&approval_prompt=&access_type=online&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile

```

**Errors:**

``` bash
Error: invalid_request
Missing required parameter: client_id
```

**Comment by patriciomacadden** [comment]
I @safarista, this project is not as active as I want. So it's not very documented...

You just have to run the server passing two environment variables, like this:

```
$ bundle exec rails s GOOGLE_KEY=yourgooglekey GOOGLE_SECRET=yourgooglesecret
```

Try that, it should be working.

**Comment by safarista** [comment]
It doesn't feel right.

Error trace

``` bash
Exiting
/Users/the-crab/.rvm/gems/ruby-1.9.2-p320@rails32/gems/rack-1.4.2/lib/rack/handler.rb:63:in `require': no such file to load -- rack/handler/google__key=<KEY-GOES-HERE> (LoadError)
    from /Users/the-crab/.rvm/gems/ruby-1.9.2-p320@rails32/gems/rack-1.4.2/lib/rack/handler.rb:63:in `try_require'
    from /Users/the-crab/.rvm/gems/ruby-1.9.2-p320@rails32/gems/rack-1.4.2/lib/rack/handler.rb:16:in `get'
    from /Users/the-crab/.rvm/gems/ruby-1.9.2-p320@rails32/gems/rack-1.4.2/lib/rack/server.rb:272:in `server'
    from /Users/the-crab/.rvm/gems/ruby-1.9.2-p320@rails32/gems/railties-3.2.9/lib/rails/commands/server.rb:59:in `start'
    from /Users/the-crab/.rvm/gems/ruby-1.9.2-p320@rails32/gems/railties-3.2.9/lib/rails/commands.rb:55:in `block in <top (required)>'
    from /Users/the-crab/.rvm/gems/ruby-1.9.2-p320@rails32/gems/railties-3.2.9/lib/rails/commands.rb:50:in `tap'
    from /Users/the-crab/.rvm/gems/ruby-1.9.2-p320@rails32/gems/railties-3.2.9/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'

```

**Comment by patriciomacadden** [comment]
Try changing the order, it worked for me:

```
GOOGLE_KEY=yourgooglekey GOOGLE_SECRET=yourgooglesecret bundle exec rails s
```
